seed: 42
project: vae
postfix: alpha
LOGGING:
  logger: 'tb'
  log_path: './logs'
  save_path: './saves'
DATA:
  name: 'CIFAR10'
  data_path: data/cifar10
  batch_size: 128
  num_workers: 4
  pin_memory: True
MODEL:
  name: VAE
  pretrained: False
  pretrain_path: ''
  latent_dim: 128
  hidden_layers: 3
  learn_prior: True
OPTIMIZER:
  name: 'adam'
  epochs: 100
  params:
    lr: 1.0e-3
    weight_decay: 0
  schedules: [60,90]
