seed: 42
project: vae_vanilla
postfix: alpha_4

DATA:
  name: MNIST
  data_path: './data'
  batch_size: 128
  num_workers: 2
  pin_memory: True

MODEL:
  name: VAEVanilla
  pretrained: False
  latent_dim: 4
  hidden_layers: 2
  learn_prior: True
  
OPTIMIZER:
  name: Adam
  epochs: 30
  params:
    lr: 0.001
    weight_decay: 0.
  schedules: [20]
    
LOGGING:
  logger: 'wandb'
  log_path: './logs'
  save_path: './saves'